# 
# Synthesis run script generated by Vivado
# 

namespace eval rt {
    variable rc
}
set rt::rc [catch {
  uplevel #0 {
    set ::env(BUILTIN_SYNTH) true
    source $::env(HRT_TCL_PATH)/rtSynthPrep.tcl
    rt::HARTNDb_resetJobStats
    rt::HARTNDb_resetSystemStats
    rt::HARTNDb_startSystemStats
    rt::HARTNDb_startJobStats
    set rt::cmdEcho 0
    rt::set_parameter writeXmsg true
    rt::set_parameter enableParallelHelperSpawn true
    set ::env(RT_TMP) "./.Xil/Vivado-73724-likhith-Inspiron-3593/realtime/tmp"
    if { [ info exists ::env(RT_TMP) ] } {
      file delete -force $::env(RT_TMP)
      file mkdir $::env(RT_TMP)
    }

    rt::delete_design

    rt::set_parameter datapathDensePacking false
    set rt::partid xc7z020clg400-1
    source $::env(HRT_TCL_PATH)/rtSynthParallelPrep.tcl
     file delete -force synth_hints.os

    set rt::multiChipSynthesisFlow false
    source $::env(SYNTH_COMMON)/common.tcl
    set rt::defaultWorkLibName xil_defaultlib

    set rt::useElabCache false
    if {$rt::useElabCache == false} {
      rt::read_verilog -sv -include {
    /home/likhith/mask_detection/mask_detection.gen/sources_1/bd/tensil_pynqz2/ipshared/f0b6/hdl/verilog
    /home/likhith/mask_detection/mask_detection.gen/sources_1/bd/tensil_pynqz2/ipshared/66be/hdl/verilog
  } {
      /home/likhith/Vivado/2022.2/data/ip/xpm/xpm_cdc/hdl/xpm_cdc.sv
      /home/likhith/Vivado/2022.2/data/ip/xpm/xpm_fifo/hdl/xpm_fifo.sv
      /home/likhith/Vivado/2022.2/data/ip/xpm/xpm_memory/hdl/xpm_memory.sv
      /home/likhith/mask_detection/mask_detection.gen/sources_1/bd/tensil_pynqz2/ipshared/f0b6/hdl/sc_util_v1_0_vl_rfs.sv
      /home/likhith/mask_detection/mask_detection.gen/sources_1/bd/tensil_pynqz2/ipshared/be1f/hdl/sc_mmu_v1_0_vl_rfs.sv
      /home/likhith/mask_detection/mask_detection.gen/sources_1/bd/tensil_pynqz2/ip/tensil_pynqz2_smartconnect_1_0/bd_0/ip/ip_2/synth/bd_a878_s00mmu_0.sv
      /home/likhith/mask_detection/mask_detection.gen/sources_1/bd/tensil_pynqz2/ipshared/4fd2/hdl/sc_transaction_regulator_v1_0_vl_rfs.sv
      /home/likhith/mask_detection/mask_detection.gen/sources_1/bd/tensil_pynqz2/ip/tensil_pynqz2_smartconnect_1_0/bd_0/ip/ip_3/synth/bd_a878_s00tr_0.sv
      /home/likhith/mask_detection/mask_detection.gen/sources_1/bd/tensil_pynqz2/ipshared/637d/hdl/sc_si_converter_v1_0_vl_rfs.sv
      /home/likhith/mask_detection/mask_detection.gen/sources_1/bd/tensil_pynqz2/ip/tensil_pynqz2_smartconnect_1_0/bd_0/ip/ip_4/synth/bd_a878_s00sic_0.sv
      /home/likhith/mask_detection/mask_detection.gen/sources_1/bd/tensil_pynqz2/ipshared/f38e/hdl/sc_axi2sc_v1_0_vl_rfs.sv
      /home/likhith/mask_detection/mask_detection.gen/sources_1/bd/tensil_pynqz2/ip/tensil_pynqz2_smartconnect_1_0/bd_0/ip/ip_5/synth/bd_a878_s00a2s_0.sv
      /home/likhith/mask_detection/mask_detection.gen/sources_1/bd/tensil_pynqz2/ipshared/66be/hdl/sc_node_v1_0_vl_rfs.sv
      /home/likhith/mask_detection/mask_detection.gen/sources_1/bd/tensil_pynqz2/ip/tensil_pynqz2_smartconnect_1_0/bd_0/ip/ip_6/synth/bd_a878_sarn_0.sv
      /home/likhith/mask_detection/mask_detection.gen/sources_1/bd/tensil_pynqz2/ip/tensil_pynqz2_smartconnect_1_0/bd_0/ip/ip_7/synth/bd_a878_srn_0.sv
      /home/likhith/mask_detection/mask_detection.gen/sources_1/bd/tensil_pynqz2/ip/tensil_pynqz2_smartconnect_1_0/bd_0/ip/ip_8/synth/bd_a878_sawn_0.sv
      /home/likhith/mask_detection/mask_detection.gen/sources_1/bd/tensil_pynqz2/ip/tensil_pynqz2_smartconnect_1_0/bd_0/ip/ip_9/synth/bd_a878_swn_0.sv
      /home/likhith/mask_detection/mask_detection.gen/sources_1/bd/tensil_pynqz2/ip/tensil_pynqz2_smartconnect_1_0/bd_0/ip/ip_10/synth/bd_a878_sbn_0.sv
      /home/likhith/mask_detection/mask_detection.gen/sources_1/bd/tensil_pynqz2/ipshared/9cc5/hdl/sc_sc2axi_v1_0_vl_rfs.sv
      /home/likhith/mask_detection/mask_detection.gen/sources_1/bd/tensil_pynqz2/ip/tensil_pynqz2_smartconnect_1_0/bd_0/ip/ip_11/synth/bd_a878_m00s2a_0.sv
      /home/likhith/mask_detection/mask_detection.gen/sources_1/bd/tensil_pynqz2/ipshared/6bba/hdl/sc_exit_v1_0_vl_rfs.sv
      /home/likhith/mask_detection/mask_detection.gen/sources_1/bd/tensil_pynqz2/ip/tensil_pynqz2_smartconnect_1_0/bd_0/ip/ip_12/synth/bd_a878_m00e_0.sv
    }
      rt::read_verilog -include {
    /home/likhith/mask_detection/mask_detection.gen/sources_1/bd/tensil_pynqz2/ipshared/f0b6/hdl/verilog
    /home/likhith/mask_detection/mask_detection.gen/sources_1/bd/tensil_pynqz2/ipshared/66be/hdl/verilog
  } {
      /home/likhith/mask_detection/mask_detection.gen/sources_1/bd/tensil_pynqz2/ipshared/badb/hdl/xlconstant_v1_1_vl_rfs.v
      /home/likhith/mask_detection/mask_detection.gen/sources_1/bd/tensil_pynqz2/ip/tensil_pynqz2_smartconnect_1_0/bd_0/ip/ip_0/synth/bd_a878_one_0.v
      /home/likhith/mask_detection/mask_detection.gen/sources_1/bd/tensil_pynqz2/ip/tensil_pynqz2_smartconnect_1_0/bd_0/synth/bd_a878.v
      /home/likhith/mask_detection/mask_detection.gen/sources_1/bd/tensil_pynqz2/ip/tensil_pynqz2_smartconnect_1_0/synth/tensil_pynqz2_smartconnect_1_0.v
    }
      rt::read_vhdl -lib xpm /home/likhith/Vivado/2022.2/data/ip/xpm/xpm_VCOMP.vhd
      rt::read_vhdl -lib lib_cdc_v1_0_2 /home/likhith/mask_detection/mask_detection.gen/sources_1/bd/tensil_pynqz2/ipshared/ef1e/hdl/lib_cdc_v1_0_rfs.vhd
      rt::read_vhdl -lib proc_sys_reset_v5_0_13 /home/likhith/mask_detection/mask_detection.gen/sources_1/bd/tensil_pynqz2/ipshared/8842/hdl/proc_sys_reset_v5_0_vh_rfs.vhd
      rt::read_vhdl -lib xil_defaultlib /home/likhith/mask_detection/mask_detection.gen/sources_1/bd/tensil_pynqz2/ip/tensil_pynqz2_smartconnect_1_0/bd_0/ip/ip_1/synth/bd_a878_psr_aclk_0.vhd
      rt::filesetChecksum
    }
    rt::set_parameter usePostFindUniquification false
    set rt::top tensil_pynqz2_smartconnect_1_0
    rt::set_parameter enableIncremental true
    rt::set_parameter markDebugPreservationLevel "enable"
    set rt::reportTiming false
    rt::set_parameter elaborateOnly true
    rt::set_parameter elaborateRtl true
    rt::set_parameter eliminateRedundantBitOperator false
    rt::set_parameter dataflowBusHighlighting false
    rt::set_parameter generateDataflowBusNetlist false
    rt::set_parameter dataFlowViewInElab false
    rt::set_parameter busViewFixBrokenConnections false
    rt::set_parameter elaborateRtlOnlyFlow false
    rt::set_parameter writeBlackboxInterface true
    rt::set_parameter merge_flipflops true
    rt::set_parameter srlDepthThreshold 3
    rt::set_parameter rstSrlDepthThreshold 4
# MODE: 
    rt::set_parameter webTalkPath {}
    rt::set_parameter synthDebugLog false
    rt::set_parameter printModuleName false
    rt::set_parameter enableSplitFlowPath "./.Xil/Vivado-73724-likhith-Inspiron-3593/"
    set ok_to_delete_rt_tmp true 
    if { [rt::get_parameter parallelDebug] } { 
       set ok_to_delete_rt_tmp false 
    } 
    if {$rt::useElabCache == false} {
        set oldMIITMVal [rt::get_parameter maxInputIncreaseToMerge]; rt::set_parameter maxInputIncreaseToMerge 1000
        set oldCDPCRL [rt::get_parameter createDfgPartConstrRecurLimit]; rt::set_parameter createDfgPartConstrRecurLimit 1
        $rt::db readXRFFile
      rt::run_rtlelab -module $rt::top
        rt::set_parameter maxInputIncreaseToMerge $oldMIITMVal
        rt::set_parameter createDfgPartConstrRecurLimit $oldCDPCRL
    }

    set rt::flowresult [ source $::env(SYNTH_COMMON)/flow.tcl ]
    rt::HARTNDb_stopJobStats
    if { $rt::flowresult == 1 } { return -code error }


    if { [ info exists ::env(RT_TMP) ] } {
      if { [info exists ok_to_delete_rt_tmp] && $ok_to_delete_rt_tmp } { 
        file delete -force $::env(RT_TMP)
      }
    }

    source $::env(HRT_TCL_PATH)/rtSynthCleanup.tcl
  } ; #end uplevel
} rt::result]

if { $rt::rc } {
  $rt::db resetHdlParse
  set hsKey [rt::get_parameter helper_shm_key] 
  if { $hsKey != "" && [info exists ::env(BUILTIN_SYNTH)] && [rt::get_parameter enableParallelHelperSpawn] } { 
     $rt::db killSynthHelper $hsKey
  } 
  source $::env(HRT_TCL_PATH)/rtSynthCleanup.tcl
  return -code "error" $rt::result
}
