# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# Block Designs: bd/tensil_pynqz2/tensil_pynqz2.bd
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==tensil_pynqz2 || ORIG_REF_NAME==tensil_pynqz2} -quiet] -quiet

# IP: bd/tensil_pynqz2/ip/tensil_pynqz2_top_pynqz1_0_0/tensil_pynqz2_top_pynqz1_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==tensil_pynqz2_top_pynqz1_0_0 || ORIG_REF_NAME==tensil_pynqz2_top_pynqz1_0_0} -quiet] -quiet

# IP: bd/tensil_pynqz2/ip/tensil_pynqz2_processing_system7_0_0/tensil_pynqz2_processing_system7_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==tensil_pynqz2_processing_system7_0_0 || ORIG_REF_NAME==tensil_pynqz2_processing_system7_0_0} -quiet] -quiet

# IP: bd/tensil_pynqz2/ip/tensil_pynqz2_smartconnect_0_0/tensil_pynqz2_smartconnect_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==tensil_pynqz2_smartconnect_0_0 || ORIG_REF_NAME==tensil_pynqz2_smartconnect_0_0} -quiet] -quiet

# IP: bd/tensil_pynqz2/ip/tensil_pynqz2_smartconnect_1_0/tensil_pynqz2_smartconnect_1_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==tensil_pynqz2_smartconnect_1_0 || ORIG_REF_NAME==tensil_pynqz2_smartconnect_1_0} -quiet] -quiet

# IP: bd/tensil_pynqz2/ip/tensil_pynqz2_smartconnect_2_0/tensil_pynqz2_smartconnect_2_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==tensil_pynqz2_smartconnect_2_0 || ORIG_REF_NAME==tensil_pynqz2_smartconnect_2_0} -quiet] -quiet

# IP: bd/tensil_pynqz2/ip/tensil_pynqz2_smartconnect_3_0/tensil_pynqz2_smartconnect_3_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==tensil_pynqz2_smartconnect_3_0 || ORIG_REF_NAME==tensil_pynqz2_smartconnect_3_0} -quiet] -quiet

# IP: bd/tensil_pynqz2/ip/tensil_pynqz2_axi_dma_0_0/tensil_pynqz2_axi_dma_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==tensil_pynqz2_axi_dma_0_0 || ORIG_REF_NAME==tensil_pynqz2_axi_dma_0_0} -quiet] -quiet

# IP: bd/tensil_pynqz2/ip/tensil_pynqz2_rst_ps7_0_50M_0/tensil_pynqz2_rst_ps7_0_50M_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==tensil_pynqz2_rst_ps7_0_50M_0 || ORIG_REF_NAME==tensil_pynqz2_rst_ps7_0_50M_0} -quiet] -quiet

# XDC: /home/likhith/mask_detection/mask_detection.gen/sources_1/bd/tensil_pynqz2/tensil_pynqz2_ooc.xdc
